// backend/src/common/enums/index.ts

export enum UserRole {
  OPERATOR = 'OPERATOR',
  MAINTENANCE = 'MAINTENANCE',
  ENGINEER = 'ENGINEER',
  ADMIN = 'ADMIN',
}

export enum MachineStatus {
  NORMAL = 'NORMAL',
  WARNING = 'WARNING',
  FAILURE = 'FAILURE',
  MAINTENANCE = 'MAINTENANCE',
}

export enum AnnotationType {
  LINE = 'LINE',
  RECTANGLE = 'RECTANGLE',
  TEXT = 'TEXT',
  CIRCLE = 'CIRCLE',
  ARROW = 'ARROW',
}

export enum EventType {
  MACHINE_STATUS_CHANGE = 'MACHINE_STATUS_CHANGE',
  ANNOTATION_CREATED = 'ANNOTATION_CREATED',
  ANNOTATION_UPDATED = 'ANNOTATION_UPDATED',
  ANNOTATION_DELETED = 'ANNOTATION_DELETED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  USER_CONNECTED = 'USER_CONNECTED',
  USER_DISCONNECTED = 'USER_DISCONNECTED',
}